---

- hosts: all
  gather_facts: yes
  sudo: yes
  roles:
    - amq

- hosts: amq01
  gather_facts: yes
  sudo: yes
  vars_files:
    - groupvars/amq
    - groupvars/amq01
  roles: 
    - amq01

- hosts: amq02
  gather_facts: yes
  sudo: yes
  vars_files:
    - groupvars/amq
    - groupvars/amq02
  roles:
    - amq02

- hosts: amq03
  gather_facts: yes
  sudo: yes
  vars_files:
    - groupvars/amq
    - groupvars/amq03
  roles:
    - amq03

- hosts: amq04
  gather_facts: yes
  sudo: yes
  vars_files:
    - groupvars/amq
    - groupvars/amq04
  roles: 
    - amq04

