Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box="trusty64"
    master.vm.hostname = 'master'
    master.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

    master.vm.network :private_network, ip: "192.168.56.101"
    master.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"
    master.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--name", "master"]
    end
  end
config.vm.provision "ansible" do |ansible|
	ansible.verbose = "v"
	ansible.playbook = "playbook.yml"
end
end
